app/models/book.py
import datetime


class Book:

    def __init__(self, title, author, pages, publish_date, description, isbn):
        self.title = title
        self.author = author
        self.pages = pages
        self.publish_date = publish_date
        self.description = description
        self.isbn = isbn

    def to_json(self):
        return {
          "title": self.title,
          "author" : self.author,
          "pages": self.pages,
          "publish_date" : datetime.datetime.strptime(str(self.publish_date), "%Y-%m-%d"),
          "description" : self.description,
          "isbn" : self.isbn
        }

app/models/rickandmorty.py
import requests

class RickandMorty:

    def __init__(self, id, name, status, species, location, image):
        self.id = id
        self.name = name
        self.status = status
        self.species = species
        self.location = location
        self.image = image

    def to_json(self):
        return {
          "id": self.id,
          "name" : self.name,
          "status": self.status,
          "species": self.species,
          "location" : self.location,
          "image" : self.image
        }


    def obtenerPersonajes():
        listaPersonajes = []
        for i in range(1,21,1):
            result = requests.get(f'https://rickandmortyapi.com/api/character?page={int(i)}')
            detailPersonaje = result.json()
            listaPersonajesXPagina = detailPersonaje['results']
            listaPersonajes.append(listaPersonajesXPagina)
        return listaPersonajes

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, DateField, IntegerField
from wtforms.validators import DataRequired


class BookForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    author = StringField("Authon", validators=[DataRequired()])
    pages = IntegerField("Pages number", validators=[DataRequired()])
    publish_date = DateField("Publish date", validators=[DataRequired()])
    description = TextAreaField("Description", validators=[DataRequired()])
    isbn = StringField("ISBN", validators=[DataRequired()])
    submit = SubmitField("Crear libro")

class RickandmortyForm(FlaskForm):
    id = IntegerField("Title", validators=[DataRequired()])
    name = StringField("Authon", validators=[DataRequired()])
    status = StringField("Pages number", validators=[DataRequired()])
    species = StringField("Publish date", validators=[DataRequired()])
    location = StringField("Description", validators=[DataRequired()])
    image = StringField("ISBN", validators=[DataRequired()])
    submit = SubmitField("Crear libro")
        

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from app.config import Config
from app.routes.book import book_router
from app.routes.rickandmorty import rickandmorty_router

def create_app():
    app=Flask(__name__)

    app.config.from_object(Config)

    Bootstrap(app)
    app.register_blueprint(rickandmorty_router)

    return app

app/routes/book.py
from flask import Blueprint, render_template, url_for, flash, redirect
from app.forms import BookForm
from app.db import db
from app.models.book import Book

book_router = Blueprint('book_router',__name__)

@book_router.route("/")
def index():
    books = db.books.find()
    return render_template("index.html",books=books)

@book_router.route("/crear", methods= ['GET','POST'])
def create_book():
    book_form=BookForm()

    if book_form.validate_on_submit():
        new_book = Book(
        book_form.title.data,
        book_form.author.data,
        book_form.pages.data,
        book_form.publish_date.data,
        book_form.description.data,
        book_form.isbn.data
        )
        db.books.insert_one(new_book.to_json())
        flash('Libro creado correctamente', 'success')
        return redirect(url_for('book_router.index'))

    return render_template("create.html", book_form=book_form)



book_router.route("/update/<id>")
def update_book(id):
  db.books.find_one_and_update({"title": id}, {"title": "new title"})

  flash("Libro eliminado", "success")

  return redirect(url_for('book_router.index'))


@book_router.route("/eliminar/<id>")
def delete_book(id):
  db.books.delete_one({"title": id})

  flash("Libro eliminado", "success")

  return redirect(url_for('book_router.index'))

  

app/routes/rickandmorty.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from app.forms import RickandmortyForm
from app.db import db
from app.models.rickandmorty import RickandMorty

rickandmorty_router = Blueprint('rickandmorty_router',__name__)

@rickandmorty_router.route("/")
def index():
    personajes = db.rickandmorty.find()
    return render_template("indexRM.html",personajes=personajes)


@rickandmorty_router.route("/obtenerPersonajes")
def obtenerPersonajes():
    personajesTotales = RickandMorty.obtenerPersonajes()        # [personajesPagina1][personajesPagina2][personajesPagina3][personajesPagina4][][]
    for personajeXpagina in personajesTotales:                  # [personajesPagina1] = [personajeID1][personajeID2][personajeID3][]
        for personaje in personajeXpagina:                      # [personajeID1] 
            new_personaje = RickandMorty(
                id=str(personaje['id']),
                name=personaje['name'],
                status=personaje['status'],
                species=personaje['species'],
                location=personaje['location'],
                image=personaje['image']
            )
            db.rickandmorty.insert_one(new_personaje.to_json())
    
    personajesDB = db.rickandmorty.find()
    return render_template("indexRM.html",personajes=personajesDB)

# Detalle del personaje
@rickandmorty_router.route("/detail/<id>",methods=['GET','POST'])
def detail_personaje(id):
    personaje = db.rickandmorty.find({"id": int(id)})
    personaje_detail = list(personaje)
    return render_template("detailRM.html",personaje=personaje_detail[0])

# Eliminar personaje
@rickandmorty_router.route("/eliminar/<id>")
def delete_personaje(id):
  db.rickandmorty.delete_one({"name": id})

  flash("Personaje eliminado", "success")

  return redirect(url_for('rickandmorty_router.index'))

# Actualizar personaje
@rickandmorty_router.route('/actualizar/<int:id>', methods=['GET', 'POST'])
def vista_actualizar(id):
    personaje = db.rickandmorty.find({"id": int(id)})
    personaje_detail = list(personaje)
    print(personaje_detail)

    if request.method == 'POST':
        updated_personaje = {
            'name': request.form["name"], 
            'status': request.form["status"],
            'species': request.form["species"] 
            , 'location.name': request.form["location"]
            }
        db.rickandmorty.update_one({'_id': personaje_detail[0]["_id"]}, {"$set": updated_personaje})
        return redirect(url_for('rickandmorty_router.index'))

    return render_template("actualizarPersonaje.html", personaje=personaje_detail[0])

app/templates/actualizarPersonaje.html
{% extends "base.html" %}

{% block content %}
<h1>Actualizar los campos del personaje: {{ personaje.id }}</h1>
<form method="POST">

  <div class="form-group">
    <label>Name:</label>
    <input value="{{personaje.name}}" type="text" name="name" class="form-control" >
  </div>

  <div class="form-group">
    <label>Status</label>
    <input value="{{ personaje.status }}" type="text" name="status" class="form-control">
  </div>

  <div class="form-group">
    <label>Species</label>
    <input value="{{ personaje.species }}" type="text" name="species" class="form-control">
  </div>
  
  <div class="form-group">
    <label>Ultima vez visto</label>
    <input value="{{ personaje.location.name }}" type="text" name="location" class="form-control">
  </div>


  <button type="submit" class="btn btn-success">Actualizar</button>

</form>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %} 

{% block body %}

<div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% for message in get_flashed_messages(category_filter=['error'])%}
    <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %} {% block content %} {% endblock %}
    </div>

    {% block scripts %} {{ super() }} 
    {% endblock %} 
{% endblock %}

app/templates/create.html
{% extends "base.html" %}

{% block content %}
  
  {% import "bootstrap/wtf.html" as wtf %}

  <h1>Crear libro</h1>

  {{ wtf.quick_form(book_form) }}

{% endblock content %}

app/templates/detailRM.html
{% extends "base.html" %} {% block content %}
    
  <div>
    regresar:
    <a href="{{ url_for('rickandmorty_router.index') }}">Pagina principal</a>
  </div>

  <h1>Personaje elegido</h1>
    ID:
    <h3>{{ personaje.id }}</h3><br>
    Name:
    <h3>{{ personaje.name }}</h3><br>
    Status:
    <h3>{{ personaje.status }}</h3><br>
    Species:
    <h3>{{ personaje.species }}</h3><br>
    Location:
    <h3>{{ personaje.location.name }}</h3><br>
    <img src="{{ personaje.image }}" width="120px" height="120px">

    
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}

<h1>Lista de libros</h1>
<a href="{{ url_for('book_router.create_book') }}">
    Crear un libro
</a>
<div class = "table-responsive">
    <table class = "table">
        <thead>
            <tr>
                <th>Autor</th>
                <th>Titulo</th>
                <th># Pages</th>
                <th>Publish date</th>
                <th>Description</th>
                <th>ISBN</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.author }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.publish_date }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.isbn }}</td>
                <td>
                  <button class="btn btn-warning">Edit</button>
                  <a
                    href="{{ url_for('book_router.delete_book', id=book.title) }}"
                    class="btn btn-danger"
                    >Delete</a
                  >
                </td>
              </tr>
            {% endfor %}
        </tbody>

    </table>
</div>




{% endblock content %}

app/templates/indexRM.html
{% extends "base.html" %} {% block content %}

<h1>Lista de personajes</h1>
<a href="{{ url_for('rickandmorty_router.obtenerPersonajes') }}">
    Cagar personajes
</a>
<div class = "table-responsive">
    <table class = "table">
        <thead>
            <tr>
                <th>id</th>
                <th>name</th>
                <th>status</th>
                <th>species</th>
                <th>location</th>
                <th>image</th>
            </tr>
        </thead>
        <tbody>
            {% for personaje in personajes %}
            <tr>
                <td>{{ personaje.id }}</td>
                <td>{{ personaje.name }}</td>
                <td>{{ personaje.status }}</td>
                <td>{{ personaje.species }}</td>
                <td>{{ personaje.location.name }}</td>
                <td><img src="{{ personaje.image }}" width="60px" height="60px"></td>
                <td>
                  <a
                    href="{{ url_for('rickandmorty_router.vista_actualizar', id=personaje.id) }}"
                    class="btn btn-warning"
                    >Editar</a
                  >
                </td>
                <td>
                  <a
                    href="{{ url_for('rickandmorty_router.detail_personaje', id=personaje.id) }}"
                    class="btn btn-info"
                    >Detail</a
                  >
                </td>
                <td>
                    <a
                      href="{{ url_for('rickandmorty_router.delete_personaje', id=personaje.name) }}"
                      class="btn btn-danger"
                      >Delete</a
                    >
                  </td>
                
              </tr>
            {% endfor %}
        </tbody>

    </table>
</div>




{% endblock content %}

app/templates/update.html
{% extends "base.html" %}

{% block content %}
<h1>El libro a actualizar es {{book.}}</h1>
<p>Mi nombre es {{ nombre }}</p>
<p>Mi appellido es {{ apellido }}</p>
<p>Mi telefono es {{ telefono }}</p>
{% endblock  %}